### ISSUE TITLE
TimerAlarm Pending intent won't let Android S+ (version 31 and above) launch

### ISSUE THREAD

**Issue by adriano-silva** [mauriciotogneri/android-utils#1]
For Android version S+ (version 31 and above) it is required to set a FLAG_IMMUTABLE or FLAG_MUTABLE on Pending intents.
Since TimerAlarm uses one, it should now specify the flag.

`   Caused by: java.lang.IllegalArgumentException: com.test.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at com.mauriciotogneri.androidutils.TimerAlarm.<init>(TimerAlarm.java:27)
        at ch.checkout.openwt.utils.TimeoutDetector.<init>(TimeoutDetector.java:23)`

**Comment by mauriciotogneri** [comment]
Hi @adriano-silva 
Sorry for the late response and thanks for the PR! I just merged it.
